[package]
name = "rust-payment-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
rusqlite = { version = "0.37.0", features = ["bundled"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_rusqlite = "0.40.0"
